= ysps3

Playing with Scala 3

== Packages review

=== concurrent

Playing with Future

* ConcurrentEx01 - manual creating execution context
* ConcurrentEx02 - using global execution context
* ConcurrentEx03 - using global execution context and Promise
* ConcurrentEx04 - using global execution context, Promise, and Await
* ConcurrentEx05 - using created execution context (with given), Promise, and Await

=== pextension
Playing with extension methods

_SomeClassForExtension_ is a class functionality of which will be extended.

_ExtensionForSomeClass_ defines the extension (converts a length to string).

_ExtRunner_ uses the extension.

=== pimplicit

==== Using implicit conversion
Playing with implicit, given.

_Second_ class defines a case class.

_ImplicitConversion_ defines the implicit conversion from _int_ to _Second_.

_TimeUtil_ uses the _Second_ object for running.

_UsageWithImplicitConversion_ is an example of the usage of implicit conversion.

==== Using extension methods

_Extension_ class defines conversion from _int_ to _Second_.

_UsageWithExtension_ is an example of the usage of extension method.
