/*
 * Copyright (c) 2022. StulSoft
 */

/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.stulsoft.ysps

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
  }

  def greeting(): String = "Hello, world!"
}
