/*
 * Copyright (c) 2022. StulSoft
 */

/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.stulsoft.ysps

import org.scalatest.funsuite.AnyFunSuite
class AppSuite extends AnyFunSuite:
  test("App has a greeting") {
    assert(App.greeting() != null)
  }
end AppSuite
